# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ecA18QjUVQSYrzp_gDGuylKtLcx3CGGO
"""

print("Hello World!")
print("Belajar AI!")
print("Yes!")